### ISSUE TITLE
Math class not sorted correctly in schedule

### ISSUE THREAD

**Issue by tjf801** [mattfrias/hubsky#1]
My linear algebra class is not in chronological order within the day, and is always at the end ([Screenshot](https://github.com/mattfrias/hubsky/assets/47402907/e2a36086-8380-46a7-8a4d-cb27263ba482))

**Comment by mattfrias** [comment]
Thanks for the feedback. I found an issue in the sorting algorithm and will be fixed in version 1.0.2 which will be released sometime this week.

Matt

**Comment by tjf801** [comment]
Nice! Thank you so much
